# Generated by Django 6.1 on 2026-08-16 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('ACTIVATE', 'Activation'), ('DEACTIVATE', 'Désactivation'), ('SUSPEND', 'Suspension'), ('PAYMENT', 'Paiement'), ('CHECK_IN', 'Entrée'), ('CHECK_OUT', 'Sortie'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('PASSWORD_CHANGE', 'Changement du mot de passe')], max_length=30, verbose_name='Action')),
                ('entity_type', models.CharField(max_length=100, verbose_name='Type d’objet')),
                ('entity_id', models.CharField(blank=True, max_length=100, verbose_name='Identifiant de l’objet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Données complémentaires')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur responsable')),
            ],
            options={
                'verbose_name': 'Journal d’audit',
                'verbose_name_plural': 'Journaux d’audit',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='audit_created_idx'), models.Index(fields=['action', 'entity_type'], name='audit_action_entity_idx')],
            },
        ),
    ]
