# Generated by Django 6.1 on 2026-08-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="coaches/"),
        ),
    ]
