# Generated by Django 6.1 on 2026-08-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_membershipplan_description_alter_payment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qr_code',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
