# Generated by Django 6.1 on 2026-08-15 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_populate_member_qr_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
